config/routes.rb
Rails.application.routes.draw do
  get '/sign_out_user', to: 'users#sign_out_user', as: 'sign_out_user'
  devise_for :users
  root 'public_recipes#index'
  resources :public_recipes, only: %i[index show]
  resources :recipes, only: %i[index show new create destroy update edit] do    
    resources :recipe_foods
  end
  resources :foods, only: %i[index show new create destroy]
  resources :general_shopping_lists, only: %i[index]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, foreign_key: 'food_id'
  has_many :recipes, through: :recipe_foods

  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :name, presence: true, length: { maximum: 250 }
  validates :measurement_unit, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, foreign_key: 'recipe_id'
  has_many :food_name, through: :recipe_foods, source: :food_name

  validates :name, presence: true, length: { maximum: 250 }
  validates :description, length: { maximum: 2000 }
  validates :preparation_time, numericality: { greater_than_or_equal_to: 0 }
  validates :cooking_time, numericality: { greater_than_or_equal_to: 0 }

  private

  def set_defaults
    self.public ||= false
  end
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe_name, class_name: 'Recipe', foreign_key: 'recipe_id'
  belongs_to :food_name, class_name: 'Food', foreign_key: 'food_id'

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def calculate_value
    self.value = quantity * food_name.price.to_f
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recipes, foreign_key: 'user_id'
  has_many :foods, foreign_key: 'user_id'

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :surname, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :surname, :email, :password, :current_password)
    end
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!

  def index
    @foods = current_user.foods
  end

  def show
    @food = current_user.foods.find(params[:id])
  end

  def new
    @food = current_user.foods.build
  end

  def create
    @food = current_user.foods.build(food_params)
    if @food.save
      redirect_to foods_path, notice: 'Food item successfully added'
    else
      render :new
    end
  end

  def destroy
    @food = current_user.foods.find(params[:id])
    @food.recipe_foods.destroy_all
    if @food.destroy
      redirect_to foods_path, notice: 'Recipe item deleted successfully.'
    else
      redirect_to foods_path, alert: 'Failed to delete the Recipe Item!'
    end
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :quantity, :price)
  end
end

app/controllers/general_shopping_lists_controller.rb
class GeneralShoppingListsController < ApplicationController
  def index
    @recipe_foods = Food.joins(
      "INNER JOIN (SELECT food_id,
                              SUM(quantity) as total_quantity,
                              SUM(value) as total_value
                       FROM recipe_foods GROUP BY food_id) as subquery
             ON foods.id = subquery.food_id"
    )
      .select('foods.name,
                     subquery.total_quantity,
                     subquery.total_value')
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @public_recipes = Recipe.where(public: true).includes(recipe_foods: :food_name)
  end

  def show
    @recipe = Recipe.includes(:user, :food_name).find(params[:id])
    @user = @recipe.user
    @foods = @recipe.food_name
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :set_recipe

  def new
    @recipe_food = @recipe.recipe_foods.new
  end

  def create
    @recipe_food = @recipe.recipe_foods.find_or_initialize_by(food_id: recipe_food_params[:food_id])
    @recipe_food.quantity = recipe_food_params[:quantity] # Set quantity
    @recipe_food.calculate_value
    if @recipe_food.save
      redirect_to @recipe, notice: 'Food added successfully.'
    else
      render :new
    end
  end

  def update
    @recipe_food = @recipe.recipe_foods.find(params[:id])
    @recipe_food.assign_attributes(recipe_food_params)

    @recipe_food.calculate_value
    if @recipe_food.save
      redirect_to @recipe, notice: 'Food updated successfully.'
    else
      flash.now[:alert] = 'Failed to Update the Food item!'
      render :edit
    end
  end

  def edit
    @recipe_food = @recipe.recipe_foods.find(params[:id])
  end

  def destroy
    @recipe_food = @recipe.recipe_foods.find(params[:id])
    if @recipe_food.destroy
      redirect_to @recipe, notice: 'Food removed successfully.'
    else
      redirect_to @recipe, alert: 'Failed to Remove Food Item!'
    end
  end

  private

  def set_recipe
    @recipe = Recipe.includes(:recipe_foods, :food_name).find(params[:recipe_id])
  end

  def recipe_food_params
    params.require(:recipe_food).permit(:food_id, :quantity, :value)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!

  def index
    @recipes = current_user.recipes.includes(:user)
  end

  def show
    @recipe = Recipe.includes(:user, :food_name).find(params[:id])
  end

  def new
    @recipe = current_user.recipes.build
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)
    if @recipe.save
      redirect_to recipes_path, notice: 'Recipe item added successfully.'
    else
      render :new
    end
  end

  def destroy
    @recipe = current_user.recipes.find(params[:id])
    @recipe.recipe_foods.destroy_all
    if @recipe.destroy
      redirect_to recipes_path, notice: 'Recipe item deleted successfully.'
    else
      redirect_to recipes_path, alert: 'Failed to delete the Recipe!'
    end
  end

  def update
    @recipe = current_user.recipes.find(params[:id])
    if @recipe.update(recipe_params)
      redirect_to @recipe, notice: 'Recipe updated successfully.'
    else
      flash.now[:alert] = 'Failed to Update the Recipe!'
      render :edit
    end
  end

  def edit
    @recipe = current_user.recipes.find(params[:id])
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :description, :cooking_time, :preparation_time, :public)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def sign_out_user
    sign_out(current_user)
    redirect_to root_path, notice: 'Signed out successfully'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_footer.html.erb
<footer class="py-5 bg-dark mt-3">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Recipe Application 2023</p>
    </div>
</footer>

app/views/application/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid mx-5">
    <%= link_to 'Recipe Application', root_path, class: 'navbar-brand' %>
    <div>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class = "nav-item">
            <%= link_to 'All Recipes', public_recipes_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Foods', foods_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'My Recipes', recipes_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Shopping List', general_shopping_lists_path, class: 'nav-link' %>
          </li>
        </ul>
        <div class="d-flex">
          <% if user_signed_in? %>
            <%= button_to 'Sign out', destroy_user_session_path, method: :delete, class: ['btn', 'btn-outline-success'] %>
          <% else %>
            <li>  <%= link_to 'Login', user_session_path, class: ['btn', 'btn-outline-success'] %></li>
            <li>  <%= link_to 'Sign up', new_user_registration_path, class: ['btn', 'btn-outline-success'] %></li>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/application/_publicrecipe.html.erb
<div class="col-md-12">
	<div class="media blog-media">
		<div class="media-body ">
		    <div class="title-name-container">
				<a href="/public_recipes/<%=recipe.id%>">
					<h1 class="mt-4 display-4">
						<%= recipe.name%>
					</h1>
				</a>
				<br/>
				<h2>By: <%= recipe.user.name %></h2>
			</div>
			<ul class="d-flex">
				<li>
					<h3>Total food items: <%= recipe.recipe_foods.count %></h3>
				</li>
                <li>
                    <h3>Total price: $<%= recipe.recipe_foods.sum { |rf| rf.quantity * rf.food_name.price } %></h3>
                </li>
			</ul>
		</div>
	</div>
</div>

app/views/application/_recipe.html.erb
<div class="col-md-12">
	<div class="media blog-media">
		<div class="media-body">
            <div class="formal-display">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6">
                            <div>
                                <a href="/recipes/<%=recipe.id%>">
                                    <h1 class="mt-4 display-4">
                                        <%= recipe.name%>
                                    </h1>
                                </a>
                                <br/>
                                <%= button_to 'REMOVE', recipe, class: 'btn btn-danger', method: :delete %>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div>
                                <p class="recipe-card-p"><%= truncate(recipe.description, length: 100, omission: '.....') %></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
		</div>
	</div>
</div>

app/views/foods/index.html.erb
<section class="my-blog bg-gradient">
    <div class="container">
		<div class="row add-food-item-action">
			<div class="col-lg-6 col-md-8 add-food-item-container">
				<div class="section-title text-center title-ex1">
					<%= link_to 'Add Food Item', new_food_path, class:'btn btn-primary'%>
				</div>
			</div>
		</div>
		<div class="row">
            <turbo-frame id="food-items-table-frame">
                <table class="table" id="FoodItemsTable">
                    <thead>
                        <tr class="tableheader">
                        <th class="tablecol sortable">Food Name</th>
                        <th class="tablecol sortable">Measurement Unit</th>
                        <th class="tablecol sortable">Price per Unit</th>
                        <th class="tablecol sortable">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @foods.each do |food| %>
                            <tr class="tableheader">
                                <td class="tablecol"><%= food.name %></td>
                                <td class="tablecol">
                                    <%= food.measurement_unit %>
                                </td>
                                <td class="tablecol">$<%= food.price %></td>
                                <td class="tablecol">
                                    <%= button_to 'REMOVE', food_path(food), method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' } %>
                                </td>
                            </tr>
                        <% end %>
                    </tbody>
                </table>
            </turbo-frame>
		</div>    
	</div>
</section>

app/views/foods/new.html.erb
<div class="new-food-form-outer-container">
  <h2>Add a New Food Item</h2>
  <%= form_with(model: @food, url: foods_path, id: "new-food-item-form") do |form| %>
    <div class="new-food-form-field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <div class="new-food-form-field">
      <%= form.label :measurement_unit %>
      <%= form.text_field :measurement_unit %>
    </div>

    <div class="new-food-form-field">
      <%= form.label :price %>
      <%= form.text_field :price %>
    </div>

    <div class="new-food-form-field">
      <%= form.label :quantity %>
      <%= form.text_field :quantity %>
    </div>

    <%= form.submit 'Add Food', id: "add-food-item-action" %>
  <% end %>
</div>

app/views/general_shopping_lists/index.html.erb
<div class="shopping-list-container">
  <h1>Shopping List</h1>

  <div class="total-foods-value">
    <p>Total Foods to Buy: <%= @recipe_foods.size %> items</p>
    <p>Total Value: $<%= @recipe_foods.sum { |rf| rf.total_value.to_i } %></p>
  </div>

  <table class="table" id="ShoppingListTable">
    <thead>
      <tr class="tableheader">
        <th class="tablecol sortable">Foods</th>
        <th class="tablecol sortable">Total Quantity</th>
        <th class="tablecol sortable">Total Value</th>
      </tr>
    </thead>
    <tbody>
      <% @recipe_foods.each do |recipe_food| %>
        <tr class="tableheader">
          <td class="tablecol"><%= recipe_food.name %></td>
          <td class="tablecol"><%= recipe_food.total_quantity %></td>
          <td class="tablecol"><%= recipe_food.total_value %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Food Recipe App</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  
  <!-- jQuery -->
  <script type="text/javascript" charset="utf8" src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

  <!-- DataTables CSS and JS -->
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.css">
  <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.js"></script>

  <!-- DataTables Bootstrap Extension JS -->
  <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap5.min.js"></script>

  <%= javascript_importmap_tags %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>

<body>
  <%= render 'application/header' %>
  <div class="container mt-2">
    <%= yield %>
  </div>

  <!-- Bootstrap Alert Components for Notice and Alert -->
  <% if notice.present? %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <%= notice %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>

  <% if alert.present? %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <%= alert %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
  <!-- End of Bootstrap Alert Components -->

  <%= render 'application/footer' %>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  <script>
    document.addEventListener('DOMContentLoaded', function () {
      // Check the initial state and apply styles accordingly
      var slider = document.querySelector('.slider');
      var publicToggleField = document.getElementById('public-toggle-field');

      if (publicToggleField.value === 'true') {
        slider.classList.add('slide');
      }
    });
    $(document).on('turbo:load', function() {
      $('#FoodIngredientsTable').DataTable();
      $('#FoodItemsTable').DataTable();
      $('#ShoppingListTable').DataTable();
    });

    function togglePublic() {
      var publicToggleField = document.getElementById('public-toggle-field');
      var toggleText = document.getElementById('toggleText');
      var slider = document.querySelector('.slider');
      var saveButton = document.getElementById('save-button');

      // Toggle the value and text based on the current state
      if (publicToggleField.value === 'true') {
        publicToggleField.value = 'false';
        toggleText.innerText = 'Toggle Public';
      } else {
        publicToggleField.value = 'true';
        toggleText.innerText = 'Toggle Private';
      }

      // Toggle the sliding effect
      slider.classList.toggle('slide');

      // Toggle the color based on the toggle state
      var toggleButtonContainer = document.querySelector('.toggle-button');
      toggleButtonContainer.classList.toggle('public-color', publicToggleField.value === 'true');

      // Automatically submit the form when the toggle state changes
      saveButton.click();
    }
  </script>
</body>
</html>

app/views/public_recipes/index.html.erb
<section class="my-blog bg-secondary bg-gradient">
    <div class="container">
		<!-- section title -->
		<div class="row justify-content-md-center">
			<div class="col-xl-5 col-lg-6 col-md-8">
				<div class="section-title text-center title-ex1 heading-info">
					<h2>Public Recipes by Users</h2>
					<p>Click the Recipe to view Details</p>
				</div>
			</div>
		</div>
		<!-- section title ends -->
		<div class="row">
			<% @public_recipes.each do |recipe| %>
            	<%= render partial: 'publicrecipe', locals: { recipe: recipe } %>
			<% end %>
		</div>    
	</div>
</section>

app/views/public_recipes/show.html.erb
<div class="each-public-recipe-container">
  <h1><%= @recipe.name %></h1>
  <p class="each-recipe-p-tag"><span class="each-recipe-span">Preparation Time: </span><%= @recipe.preparation_time %></p>
  <p class="each-recipe-p-tag"><span class="each-recipe-span">Cooking Time: </span><%= @recipe.cooking_time %></p>
  <p class="each-recipe-p-tag"><span class="each-recipe-span">Description: </span><%= @recipe.description %></p>

  <h2 class="lefth2">Ingredients</h2>
  <table id="FoodIngredientsTable" class="table">
    <thead>
      <tr class="tableheader">
        <th class="colheading sortable">Foods</th>
        <th class="colheading sortable">Quantity</th>
        <th class="colheading sortable">Value</th>
      </tr>
    </thead>
    <tbody>
      <% @recipe.recipe_foods.each do |recipe_food| %>
        <tr class="tableheader">
          <td class="tablecol"><%= recipe_food.food_name.name %></td>
          <td class="tablecol"><%= recipe_food.quantity %><%= recipe_food.food_name.measurement_unit %></td>
          <td class="tablecol">$<%= recipe_food.value %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/recipe_foods/edit.html.erb
<h2>Update Food Quantity</h2>
<%= form_with(model: [@recipe, @recipe_food], local: true) do |form| %>
    <%= form.number_field :quantity, min: 1 %>
    <%= form.submit "Update Food" %>
  <% end %>
  
<%= link_to 'Cancel', recipe_path(@recipe)%>

app/views/recipe_foods/new.html.erb
<div class="new-food-container">
  <h2>Add Ingredients needed for Recipe</h2>

  <%= form_with(model: [@recipe, @recipe_food], local: true, id: "recipe-add-food-form") do |form| %>
    <div class="field">
      <%= form.label :food_id, "Food" %>
      <%= form.collection_select(:food_id, Food.all, :id, :name, prompt: "Select food Item") %>
    </div>
    <div class="field">
      <%= form.label :quantity %>
      <%= form.number_field :quantity %>
    </div>

    <%= form.submit "Add Food", id: "add-food-action" %>
  <% end %>
</div>

app/views/recipes/index.html.erb
<section class="my-blog bg-secondary bg-gradient">
    <div class="container">
		<div class="row add-recipe-action-container">
			<div class="col-xl-5 col-lg-6 col-md-8">
				<div class="section-title text-center title-ex1">
					<%= link_to 'Add New recipe', new_recipe_path, class:'btn btn-primary'%>
				</div>
			</div>
		</div>
		<div class="row">
			<% @recipes.each do |recipe| %>
            	<%= render partial: 'recipe', locals: { recipe: recipe } %>
			<% end %>
		</div>    
	</div>
</section>

app/views/recipes/new.html.erb
<div class="new-recipe-container">
  <h1>Add a New Recipe Item</h1>
  <%= form_with(model: @recipe, url: recipes_path, id: "add-new-recipe-form") do |form| %>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <div class="field">
      <%= form.label :preparation_time %>
      <%= form.text_field :preparation_time %>
    </div>

    <div class="field">
      <%= form.label :cooking_time %>
      <%= form.text_field :cooking_time %>
    </div>

    <div class="field">
      <%= form.label :description %>
      <%= form.text_field :description %>
    </div>

    <div class="public-checkbox">
      <%= form.label :public %>
      <%= form.check_box :public %>
    </div>

    <%= form.submit 'Add Recipe', id: "add-recipe-action" %>
  <% end %>
</div>

app/views/recipes/show.html.erb
<div class="each-recipe-container">
  <div class="container recipe-inner-container">
    <div class="row">
      <h1><%= @recipe.name %></h1>
      <div class="col-md-6">
        <p>Preparation Time: <%= @recipe.preparation_time %></p>
        <p>Cooking Time: <%= @recipe.cooking_time %></p>
        <p>Description: <%= @recipe.description %></p>
      </div>
      <div class="col-md-6">
        <div class="formatrecipeview">
          <div class="makepublicform">
            <%= form_with(model: @recipe, url: recipe_path(@recipe), method:
            :patch) do |form| %>
            <div
              class="toggle-button-container d-flex align-items-center justify-content-around"
              onclick="togglePublic();"
            >
              <span class="toggle-text" id="toggleText">
                <%= @recipe.public ? 'Toggle Private' : 'Toggle Public' %>
              </span>
              <%= form.hidden_field :public, value: @recipe.public, id:
              'public-toggle-field' %> <%= form.label :public, class:
              'toggle-button', for: 'public-toggle-field' do %>
              <div class="slider <%= 'slide' if @recipe.public %>"></div>
              <% end %>
            </div>
            <%= form.submit "Save", id: 'save-button', style: 'display: none;' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="formatrecipeview">
    <div class="container">
      <div class="row recipe-ingredients-container">
        <div class="col-md-6 shop-items-container">
          <%= link_to 'Generate General Shopping List',
          general_shopping_lists_path, class:'btn btn-secondary' %>
        </div>
        <div class="col-md-6 shop-items-container">
          <%= link_to 'Add Ingredients', new_recipe_recipe_food_path(@recipe),
          class:'btn btn-secondary' %>
        </div>
      </div>
    </div>
  </div>
  <!-- Bootstrap Table for Ingredients -->
  <h2 class="lefth2">Ingredients</h2>
  <table class="table" id="RecipeIngredientsTable">
    <thead>
      <tr class="tableheader">
        <th class="tablecol sortable">Foods</th>
        <th class="tablecol sortable">Quantity</th>
        <th class="tablecol sortable">Value</th>
        <th class="tablecol sortable">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @recipe.recipe_foods.each do |recipe_food| %>
      <tr class="tableheader">
        <td class="tablecol"><%= recipe_food.food_name.name %></td>
        <td class="tablecol">
          <%= recipe_food.quantity %><%= recipe_food.food_name.measurement_unit %>
        </td>
        <td class="tablecol">$<%= recipe_food.value %></td>
        <td class="tablecol modify-delete-actions">
          <%= link_to 'Modify', edit_recipe_recipe_food_path(@recipe,
          recipe_food), class:'btn btn-secondary' %>
          <%= button_to 'Remove',
          recipe_recipe_food_path(@recipe, recipe_food), class:'btn
          btn-secondary', method: :delete %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>